
build-ch:
	go build -buildmode=plugin -o chinese/greet.so chinese/greet.go

build-en:
	go build -buildmode=plugin -o english/greet.so english/greet.go

build-panic:
	go build -buildmode=plugin -o panic/greet.so panic/greet.go