// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexdemo

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type LogLevel int64

const (
	LogLevel_DEBUG LogLevel = 0
	LogLevel_INFO  LogLevel = 1
	LogLevel_WARN  LogLevel = 2
	LogLevel_ERROR LogLevel = 3
)

func (p LogLevel) String() string {
	switch p {
	case LogLevel_DEBUG:
		return "DEBUG"
	case LogLevel_INFO:
		return "INFO"
	case LogLevel_WARN:
		return "WARN"
	case LogLevel_ERROR:
		return "ERROR"
	}
	return "<UNSET>"
}

func LogLevelFromString(s string) (LogLevel, error) {
	switch s {
	case "DEBUG":
		return LogLevel_DEBUG, nil
	case "INFO":
		return LogLevel_INFO, nil
	case "WARN":
		return LogLevel_WARN, nil
	case "ERROR":
		return LogLevel_ERROR, nil
	}
	return LogLevel(0), fmt.Errorf("not a valid LogLevel string")
}

func LogLevelPtr(v LogLevel) *LogLevel { return &v }
func (p *LogLevel) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = LogLevel(result.Int64)
	return
}

func (p *LogLevel) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type UserRole int64

const (
	UserRole_GUEST UserRole = 0
	UserRole_USER  UserRole = 1
	UserRole_ADMIN UserRole = 2
)

func (p UserRole) String() string {
	switch p {
	case UserRole_GUEST:
		return "GUEST"
	case UserRole_USER:
		return "USER"
	case UserRole_ADMIN:
		return "ADMIN"
	}
	return "<UNSET>"
}

func UserRoleFromString(s string) (UserRole, error) {
	switch s {
	case "GUEST":
		return UserRole_GUEST, nil
	case "USER":
		return UserRole_USER, nil
	case "ADMIN":
		return UserRole_ADMIN, nil
	}
	return UserRole(0), fmt.Errorf("not a valid UserRole string")
}

func UserRolePtr(v UserRole) *UserRole { return &v }
func (p *UserRole) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = UserRole(result.Int64)
	return
}

func (p *UserRole) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type EchoRequest struct {
	Message   string `thrift:"message,1,required" frugal:"1,required,string" json:"message"`
	Timestamp *int64 `thrift:"timestamp,2,optional" frugal:"2,optional,i64" json:"timestamp,omitempty"`
}

func NewEchoRequest() *EchoRequest {
	return &EchoRequest{}
}

func (p *EchoRequest) InitDefault() {
}

func (p *EchoRequest) GetMessage() (v string) {
	return p.Message
}

var EchoRequest_Timestamp_DEFAULT int64

func (p *EchoRequest) GetTimestamp() (v int64) {
	if !p.IsSetTimestamp() {
		return EchoRequest_Timestamp_DEFAULT
	}
	return *p.Timestamp
}
func (p *EchoRequest) SetMessage(val string) {
	p.Message = val
}
func (p *EchoRequest) SetTimestamp(val *int64) {
	p.Timestamp = val
}

func (p *EchoRequest) IsSetTimestamp() bool {
	return p.Timestamp != nil
}

func (p *EchoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoRequest(%+v)", *p)
}

var fieldIDToName_EchoRequest = map[int16]string{
	1: "message",
	2: "timestamp",
}

type EchoResponse struct {
	Message   string  `thrift:"message,1,required" frugal:"1,required,string" json:"message"`
	ElapsedMs int64   `thrift:"elapsed_ms,2,required" frugal:"2,required,i64" json:"elapsed_ms"`
	ServerId  *string `thrift:"server_id,3,optional" frugal:"3,optional,string" json:"server_id,omitempty"`
}

func NewEchoResponse() *EchoResponse {
	return &EchoResponse{}
}

func (p *EchoResponse) InitDefault() {
}

func (p *EchoResponse) GetMessage() (v string) {
	return p.Message
}

func (p *EchoResponse) GetElapsedMs() (v int64) {
	return p.ElapsedMs
}

var EchoResponse_ServerId_DEFAULT string

func (p *EchoResponse) GetServerId() (v string) {
	if !p.IsSetServerId() {
		return EchoResponse_ServerId_DEFAULT
	}
	return *p.ServerId
}
func (p *EchoResponse) SetMessage(val string) {
	p.Message = val
}
func (p *EchoResponse) SetElapsedMs(val int64) {
	p.ElapsedMs = val
}
func (p *EchoResponse) SetServerId(val *string) {
	p.ServerId = val
}

func (p *EchoResponse) IsSetServerId() bool {
	return p.ServerId != nil
}

func (p *EchoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoResponse(%+v)", *p)
}

var fieldIDToName_EchoResponse = map[int16]string{
	1: "message",
	2: "elapsed_ms",
	3: "server_id",
}

type User struct {
	Id          string            `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Name        string            `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Age         int32             `thrift:"age,3,required" frugal:"3,required,i32" json:"age"`
	Email       *string           `thrift:"email,4,optional" frugal:"4,optional,string" json:"email,omitempty"`
	Role        *UserRole         `thrift:"role,5,optional" frugal:"5,optional,UserRole" json:"role,omitempty"`
	Tags        map[string]string `thrift:"tags,6,optional" frugal:"6,optional,map<string:string>" json:"tags,omitempty"`
	Permissions []string          `thrift:"permissions,7,optional" frugal:"7,optional,list<string>" json:"permissions,omitempty"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v string) {
	return p.Id
}

func (p *User) GetName() (v string) {
	return p.Name
}

func (p *User) GetAge() (v int32) {
	return p.Age
}

var User_Email_DEFAULT string

func (p *User) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return User_Email_DEFAULT
	}
	return *p.Email
}

var User_Role_DEFAULT UserRole

func (p *User) GetRole() (v UserRole) {
	if !p.IsSetRole() {
		return User_Role_DEFAULT
	}
	return *p.Role
}

var User_Tags_DEFAULT map[string]string

func (p *User) GetTags() (v map[string]string) {
	if !p.IsSetTags() {
		return User_Tags_DEFAULT
	}
	return p.Tags
}

var User_Permissions_DEFAULT []string

func (p *User) GetPermissions() (v []string) {
	if !p.IsSetPermissions() {
		return User_Permissions_DEFAULT
	}
	return p.Permissions
}
func (p *User) SetId(val string) {
	p.Id = val
}
func (p *User) SetName(val string) {
	p.Name = val
}
func (p *User) SetAge(val int32) {
	p.Age = val
}
func (p *User) SetEmail(val *string) {
	p.Email = val
}
func (p *User) SetRole(val *UserRole) {
	p.Role = val
}
func (p *User) SetTags(val map[string]string) {
	p.Tags = val
}
func (p *User) SetPermissions(val []string) {
	p.Permissions = val
}

func (p *User) IsSetEmail() bool {
	return p.Email != nil
}

func (p *User) IsSetRole() bool {
	return p.Role != nil
}

func (p *User) IsSetTags() bool {
	return p.Tags != nil
}

func (p *User) IsSetPermissions() bool {
	return p.Permissions != nil
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "name",
	3: "age",
	4: "email",
	5: "role",
	6: "tags",
	7: "permissions",
}

type GetUserRequest struct {
	UserId string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
}

func NewGetUserRequest() *GetUserRequest {
	return &GetUserRequest{}
}

func (p *GetUserRequest) InitDefault() {
}

func (p *GetUserRequest) GetUserId() (v string) {
	return p.UserId
}
func (p *GetUserRequest) SetUserId(val string) {
	p.UserId = val
}

func (p *GetUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRequest(%+v)", *p)
}

var fieldIDToName_GetUserRequest = map[int16]string{
	1: "user_id",
}

type GetUserResponse struct {
	User *User `thrift:"user,1,required" frugal:"1,required,User" json:"user"`
}

func NewGetUserResponse() *GetUserResponse {
	return &GetUserResponse{}
}

func (p *GetUserResponse) InitDefault() {
}

var GetUserResponse_User_DEFAULT *User

func (p *GetUserResponse) GetUser() (v *User) {
	if !p.IsSetUser() {
		return GetUserResponse_User_DEFAULT
	}
	return p.User
}
func (p *GetUserResponse) SetUser(val *User) {
	p.User = val
}

func (p *GetUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResponse(%+v)", *p)
}

var fieldIDToName_GetUserResponse = map[int16]string{
	1: "user",
}

type ListUsersRequest struct {
	Page     *int32  `thrift:"page,1,optional" frugal:"1,optional,i32" json:"page,omitempty"`
	PageSize *int32  `thrift:"page_size,2,optional" frugal:"2,optional,i32" json:"page_size,omitempty"`
	Filter   *string `thrift:"filter,3,optional" frugal:"3,optional,string" json:"filter,omitempty"`
}

func NewListUsersRequest() *ListUsersRequest {
	return &ListUsersRequest{}
}

func (p *ListUsersRequest) InitDefault() {
}

var ListUsersRequest_Page_DEFAULT int32

func (p *ListUsersRequest) GetPage() (v int32) {
	if !p.IsSetPage() {
		return ListUsersRequest_Page_DEFAULT
	}
	return *p.Page
}

var ListUsersRequest_PageSize_DEFAULT int32

func (p *ListUsersRequest) GetPageSize() (v int32) {
	if !p.IsSetPageSize() {
		return ListUsersRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

var ListUsersRequest_Filter_DEFAULT string

func (p *ListUsersRequest) GetFilter() (v string) {
	if !p.IsSetFilter() {
		return ListUsersRequest_Filter_DEFAULT
	}
	return *p.Filter
}
func (p *ListUsersRequest) SetPage(val *int32) {
	p.Page = val
}
func (p *ListUsersRequest) SetPageSize(val *int32) {
	p.PageSize = val
}
func (p *ListUsersRequest) SetFilter(val *string) {
	p.Filter = val
}

func (p *ListUsersRequest) IsSetPage() bool {
	return p.Page != nil
}

func (p *ListUsersRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *ListUsersRequest) IsSetFilter() bool {
	return p.Filter != nil
}

func (p *ListUsersRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListUsersRequest(%+v)", *p)
}

var fieldIDToName_ListUsersRequest = map[int16]string{
	1: "page",
	2: "page_size",
	3: "filter",
}

type ListUsersResponse struct {
	Users []*User `thrift:"users,1,required" frugal:"1,required,list<User>" json:"users"`
	Total int32   `thrift:"total,2,required" frugal:"2,required,i32" json:"total"`
}

func NewListUsersResponse() *ListUsersResponse {
	return &ListUsersResponse{}
}

func (p *ListUsersResponse) InitDefault() {
}

func (p *ListUsersResponse) GetUsers() (v []*User) {
	return p.Users
}

func (p *ListUsersResponse) GetTotal() (v int32) {
	return p.Total
}
func (p *ListUsersResponse) SetUsers(val []*User) {
	p.Users = val
}
func (p *ListUsersResponse) SetTotal(val int32) {
	p.Total = val
}

func (p *ListUsersResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListUsersResponse(%+v)", *p)
}

var fieldIDToName_ListUsersResponse = map[int16]string{
	1: "users",
	2: "total",
}

type LogEventRequest struct {
	Event       string            `thrift:"event,1,required" frugal:"1,required,string" json:"event"`
	Level       LogLevel          `thrift:"level,2,required" frugal:"2,required,LogLevel" json:"level"`
	ContextData map[string]string `thrift:"context_data,3,optional" frugal:"3,optional,map<string:string>" json:"context_data,omitempty"`
}

func NewLogEventRequest() *LogEventRequest {
	return &LogEventRequest{}
}

func (p *LogEventRequest) InitDefault() {
}

func (p *LogEventRequest) GetEvent() (v string) {
	return p.Event
}

func (p *LogEventRequest) GetLevel() (v LogLevel) {
	return p.Level
}

var LogEventRequest_ContextData_DEFAULT map[string]string

func (p *LogEventRequest) GetContextData() (v map[string]string) {
	if !p.IsSetContextData() {
		return LogEventRequest_ContextData_DEFAULT
	}
	return p.ContextData
}
func (p *LogEventRequest) SetEvent(val string) {
	p.Event = val
}
func (p *LogEventRequest) SetLevel(val LogLevel) {
	p.Level = val
}
func (p *LogEventRequest) SetContextData(val map[string]string) {
	p.ContextData = val
}

func (p *LogEventRequest) IsSetContextData() bool {
	return p.ContextData != nil
}

func (p *LogEventRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogEventRequest(%+v)", *p)
}

var fieldIDToName_LogEventRequest = map[int16]string{
	1: "event",
	2: "level",
	3: "context_data",
}

type ServiceException struct {
	Code    int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Message string  `thrift:"message,2,required" frugal:"2,required,string" json:"message"`
	Details *string `thrift:"details,3,optional" frugal:"3,optional,string" json:"details,omitempty"`
}

func NewServiceException() *ServiceException {
	return &ServiceException{}
}

func (p *ServiceException) InitDefault() {
}

func (p *ServiceException) GetCode() (v int32) {
	return p.Code
}

func (p *ServiceException) GetMessage() (v string) {
	return p.Message
}

var ServiceException_Details_DEFAULT string

func (p *ServiceException) GetDetails() (v string) {
	if !p.IsSetDetails() {
		return ServiceException_Details_DEFAULT
	}
	return *p.Details
}
func (p *ServiceException) SetCode(val int32) {
	p.Code = val
}
func (p *ServiceException) SetMessage(val string) {
	p.Message = val
}
func (p *ServiceException) SetDetails(val *string) {
	p.Details = val
}

func (p *ServiceException) IsSetDetails() bool {
	return p.Details != nil
}

func (p *ServiceException) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceException(%+v)", *p)
}
func (p *ServiceException) Error() string {
	return p.String()
}

var fieldIDToName_ServiceException = map[int16]string{
	1: "code",
	2: "message",
	3: "details",
}

type NotFoundException struct {
	Resource string `thrift:"resource,1,required" frugal:"1,required,string" json:"resource"`
	Id       string `thrift:"id,2,required" frugal:"2,required,string" json:"id"`
}

func NewNotFoundException() *NotFoundException {
	return &NotFoundException{}
}

func (p *NotFoundException) InitDefault() {
}

func (p *NotFoundException) GetResource() (v string) {
	return p.Resource
}

func (p *NotFoundException) GetId() (v string) {
	return p.Id
}
func (p *NotFoundException) SetResource(val string) {
	p.Resource = val
}
func (p *NotFoundException) SetId(val string) {
	p.Id = val
}

func (p *NotFoundException) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NotFoundException(%+v)", *p)
}
func (p *NotFoundException) Error() string {
	return p.String()
}

var fieldIDToName_NotFoundException = map[int16]string{
	1: "resource",
	2: "id",
}

type UserService interface {
	Echo(ctx context.Context, req *EchoRequest) (r *EchoResponse, err error)

	GetUser(ctx context.Context, req *GetUserRequest) (r *GetUserResponse, err error)

	ListUsers(ctx context.Context, req *ListUsersRequest) (r *ListUsersResponse, err error)

	LogEvent(ctx context.Context, req *LogEventRequest) (err error)
}

type UserServiceEchoArgs struct {
	Req *EchoRequest `thrift:"req,1" frugal:"1,default,EchoRequest" json:"req"`
}

func NewUserServiceEchoArgs() *UserServiceEchoArgs {
	return &UserServiceEchoArgs{}
}

func (p *UserServiceEchoArgs) InitDefault() {
}

var UserServiceEchoArgs_Req_DEFAULT *EchoRequest

func (p *UserServiceEchoArgs) GetReq() (v *EchoRequest) {
	if !p.IsSetReq() {
		return UserServiceEchoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceEchoArgs) SetReq(val *EchoRequest) {
	p.Req = val
}

func (p *UserServiceEchoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceEchoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceEchoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceEchoArgs = map[int16]string{
	1: "req",
}

type UserServiceEchoResult struct {
	Success *EchoResponse     `thrift:"success,0,optional" frugal:"0,optional,EchoResponse" json:"success,omitempty"`
	Err     *ServiceException `thrift:"err,1,optional" frugal:"1,optional,ServiceException" json:"err,omitempty"`
}

func NewUserServiceEchoResult() *UserServiceEchoResult {
	return &UserServiceEchoResult{}
}

func (p *UserServiceEchoResult) InitDefault() {
}

var UserServiceEchoResult_Success_DEFAULT *EchoResponse

func (p *UserServiceEchoResult) GetSuccess() (v *EchoResponse) {
	if !p.IsSetSuccess() {
		return UserServiceEchoResult_Success_DEFAULT
	}
	return p.Success
}

var UserServiceEchoResult_Err_DEFAULT *ServiceException

func (p *UserServiceEchoResult) GetErr() (v *ServiceException) {
	if !p.IsSetErr() {
		return UserServiceEchoResult_Err_DEFAULT
	}
	return p.Err
}
func (p *UserServiceEchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*EchoResponse)
}
func (p *UserServiceEchoResult) SetErr(val *ServiceException) {
	p.Err = val
}

func (p *UserServiceEchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceEchoResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *UserServiceEchoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceEchoResult(%+v)", *p)
}

var fieldIDToName_UserServiceEchoResult = map[int16]string{
	0: "success",
	1: "err",
}

type UserServiceGetUserArgs struct {
	Req *GetUserRequest `thrift:"req,1" frugal:"1,default,GetUserRequest" json:"req"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Req_DEFAULT *GetUserRequest

func (p *UserServiceGetUserArgs) GetReq() (v *GetUserRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserArgs) SetReq(val *GetUserRequest) {
	p.Req = val
}

func (p *UserServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserResult struct {
	Success  *GetUserResponse   `thrift:"success,0,optional" frugal:"0,optional,GetUserResponse" json:"success,omitempty"`
	Err      *ServiceException  `thrift:"err,1,optional" frugal:"1,optional,ServiceException" json:"err,omitempty"`
	NotFound *NotFoundException `thrift:"notFound,2,optional" frugal:"2,optional,NotFoundException" json:"notFound,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}

var UserServiceGetUserResult_Err_DEFAULT *ServiceException

func (p *UserServiceGetUserResult) GetErr() (v *ServiceException) {
	if !p.IsSetErr() {
		return UserServiceGetUserResult_Err_DEFAULT
	}
	return p.Err
}

var UserServiceGetUserResult_NotFound_DEFAULT *NotFoundException

func (p *UserServiceGetUserResult) GetNotFound() (v *NotFoundException) {
	if !p.IsSetNotFound() {
		return UserServiceGetUserResult_NotFound_DEFAULT
	}
	return p.NotFound
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResponse)
}
func (p *UserServiceGetUserResult) SetErr(val *ServiceException) {
	p.Err = val
}
func (p *UserServiceGetUserResult) SetNotFound(val *NotFoundException) {
	p.NotFound = val
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *UserServiceGetUserResult) IsSetNotFound() bool {
	return p.NotFound != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
	1: "err",
	2: "notFound",
}

type UserServiceListUsersArgs struct {
	Req *ListUsersRequest `thrift:"req,1" frugal:"1,default,ListUsersRequest" json:"req"`
}

func NewUserServiceListUsersArgs() *UserServiceListUsersArgs {
	return &UserServiceListUsersArgs{}
}

func (p *UserServiceListUsersArgs) InitDefault() {
}

var UserServiceListUsersArgs_Req_DEFAULT *ListUsersRequest

func (p *UserServiceListUsersArgs) GetReq() (v *ListUsersRequest) {
	if !p.IsSetReq() {
		return UserServiceListUsersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceListUsersArgs) SetReq(val *ListUsersRequest) {
	p.Req = val
}

func (p *UserServiceListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceListUsersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListUsersArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListUsersArgs = map[int16]string{
	1: "req",
}

type UserServiceListUsersResult struct {
	Success *ListUsersResponse `thrift:"success,0,optional" frugal:"0,optional,ListUsersResponse" json:"success,omitempty"`
	Err     *ServiceException  `thrift:"err,1,optional" frugal:"1,optional,ServiceException" json:"err,omitempty"`
}

func NewUserServiceListUsersResult() *UserServiceListUsersResult {
	return &UserServiceListUsersResult{}
}

func (p *UserServiceListUsersResult) InitDefault() {
}

var UserServiceListUsersResult_Success_DEFAULT *ListUsersResponse

func (p *UserServiceListUsersResult) GetSuccess() (v *ListUsersResponse) {
	if !p.IsSetSuccess() {
		return UserServiceListUsersResult_Success_DEFAULT
	}
	return p.Success
}

var UserServiceListUsersResult_Err_DEFAULT *ServiceException

func (p *UserServiceListUsersResult) GetErr() (v *ServiceException) {
	if !p.IsSetErr() {
		return UserServiceListUsersResult_Err_DEFAULT
	}
	return p.Err
}
func (p *UserServiceListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListUsersResponse)
}
func (p *UserServiceListUsersResult) SetErr(val *ServiceException) {
	p.Err = val
}

func (p *UserServiceListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListUsersResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *UserServiceListUsersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListUsersResult(%+v)", *p)
}

var fieldIDToName_UserServiceListUsersResult = map[int16]string{
	0: "success",
	1: "err",
}

type UserServiceLogEventArgs struct {
	Req *LogEventRequest `thrift:"req,1" frugal:"1,default,LogEventRequest" json:"req"`
}

func NewUserServiceLogEventArgs() *UserServiceLogEventArgs {
	return &UserServiceLogEventArgs{}
}

func (p *UserServiceLogEventArgs) InitDefault() {
}

var UserServiceLogEventArgs_Req_DEFAULT *LogEventRequest

func (p *UserServiceLogEventArgs) GetReq() (v *LogEventRequest) {
	if !p.IsSetReq() {
		return UserServiceLogEventArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLogEventArgs) SetReq(val *LogEventRequest) {
	p.Req = val
}

func (p *UserServiceLogEventArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLogEventArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogEventArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLogEventArgs = map[int16]string{
	1: "req",
}

// exceptions of methods in UserService.
var (
	_ error = (*NotFoundException)(nil)
	_ error = (*ServiceException)(nil)
)
