// Code generated by Kitex v0.16.0. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	kitexdemo "github.com/liuliqiang/blog_codes/rpc/kitex/kitex_gen/kitexdemo"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Echo(ctx context.Context, req *kitexdemo.EchoRequest, callOptions ...callopt.Option) (r *kitexdemo.EchoResponse, err error)
	GetUser(ctx context.Context, req *kitexdemo.GetUserRequest, callOptions ...callopt.Option) (r *kitexdemo.GetUserResponse, err error)
	ListUsers(ctx context.Context, req *kitexdemo.ListUsersRequest, callOptions ...callopt.Option) (r *kitexdemo.ListUsersResponse, err error)
	LogEvent(ctx context.Context, req *kitexdemo.LogEventRequest, callOptions ...callopt.Option) (err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Echo(ctx context.Context, req *kitexdemo.EchoRequest, callOptions ...callopt.Option) (r *kitexdemo.EchoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Echo(ctx, req)
}

func (p *kUserServiceClient) GetUser(ctx context.Context, req *kitexdemo.GetUserRequest, callOptions ...callopt.Option) (r *kitexdemo.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, req)
}

func (p *kUserServiceClient) ListUsers(ctx context.Context, req *kitexdemo.ListUsersRequest, callOptions ...callopt.Option) (r *kitexdemo.ListUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, req)
}

func (p *kUserServiceClient) LogEvent(ctx context.Context, req *kitexdemo.LogEventRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LogEvent(ctx, req)
}
