// Code generated by Kitex v0.16.0. DO NOT EDIT.
package userservice

import (
	server "github.com/cloudwego/kitex/server"
	kitexdemo "github.com/liuliqiang/blog_codes/rpc/kitex/kitex_gen/kitexdemo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kitexdemo.UserService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler kitexdemo.UserService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
