// Code generated by Kitex v0.16.0. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	kitexdemo "github.com/liuliqiang/blog_codes/rpc/kitex/kitex_gen/kitexdemo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Echo": kitex.NewMethodInfo(
		echoHandler,
		newUserServiceEchoArgs,
		newUserServiceEchoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUser": kitex.NewMethodInfo(
		getUserHandler,
		newUserServiceGetUserArgs,
		newUserServiceGetUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListUsers": kitex.NewMethodInfo(
		listUsersHandler,
		newUserServiceListUsersArgs,
		newUserServiceListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LogEvent": kitex.NewMethodInfo(
		logEventHandler,
		newUserServiceLogEventArgs,
		nil,
		true,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*kitexdemo.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexdemo",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.0",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexdemo.UserServiceEchoArgs)
	realResult := result.(*kitexdemo.UserServiceEchoResult)
	success, err := handler.(kitexdemo.UserService).Echo(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *kitexdemo.ServiceException:
			realResult.Err = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newUserServiceEchoArgs() interface{} {
	return kitexdemo.NewUserServiceEchoArgs()
}

func newUserServiceEchoResult() interface{} {
	return kitexdemo.NewUserServiceEchoResult()
}

func getUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexdemo.UserServiceGetUserArgs)
	realResult := result.(*kitexdemo.UserServiceGetUserResult)
	success, err := handler.(kitexdemo.UserService).GetUser(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *kitexdemo.ServiceException:
			realResult.Err = v
		case *kitexdemo.NotFoundException:
			realResult.NotFound = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newUserServiceGetUserArgs() interface{} {
	return kitexdemo.NewUserServiceGetUserArgs()
}

func newUserServiceGetUserResult() interface{} {
	return kitexdemo.NewUserServiceGetUserResult()
}

func listUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexdemo.UserServiceListUsersArgs)
	realResult := result.(*kitexdemo.UserServiceListUsersResult)
	success, err := handler.(kitexdemo.UserService).ListUsers(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *kitexdemo.ServiceException:
			realResult.Err = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newUserServiceListUsersArgs() interface{} {
	return kitexdemo.NewUserServiceListUsersArgs()
}

func newUserServiceListUsersResult() interface{} {
	return kitexdemo.NewUserServiceListUsersResult()
}

func logEventHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexdemo.UserServiceLogEventArgs)

	err := handler.(kitexdemo.UserService).LogEvent(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newUserServiceLogEventArgs() interface{} {
	return kitexdemo.NewUserServiceLogEventArgs()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req *kitexdemo.EchoRequest) (r *kitexdemo.EchoResponse, err error) {
	var _args kitexdemo.UserServiceEchoArgs
	_args.Req = req
	var _result kitexdemo.UserServiceEchoResult
	if err = p.c.Call(ctx, "Echo", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Err != nil:
		return r, _result.Err
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUser(ctx context.Context, req *kitexdemo.GetUserRequest) (r *kitexdemo.GetUserResponse, err error) {
	var _args kitexdemo.UserServiceGetUserArgs
	_args.Req = req
	var _result kitexdemo.UserServiceGetUserResult
	if err = p.c.Call(ctx, "GetUser", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Err != nil:
		return r, _result.Err
	case _result.NotFound != nil:
		return r, _result.NotFound
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListUsers(ctx context.Context, req *kitexdemo.ListUsersRequest) (r *kitexdemo.ListUsersResponse, err error) {
	var _args kitexdemo.UserServiceListUsersArgs
	_args.Req = req
	var _result kitexdemo.UserServiceListUsersResult
	if err = p.c.Call(ctx, "ListUsers", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Err != nil:
		return r, _result.Err
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LogEvent(ctx context.Context, req *kitexdemo.LogEventRequest) (err error) {
	var _args kitexdemo.UserServiceLogEventArgs
	_args.Req = req
	if err = p.c.Call(ctx, "LogEvent", &_args, nil); err != nil {
		return
	}
	return nil
}
