
so:
	go build -buildmode=plugin -o eng/eng.so eng/greeter.go
	go build -buildmode=plugin -o chi/chi.so chi/greeter.go
	go build -buildmode=plugin -o swe/swe.so swe/greeter.go

english:
	go run greeter.go  -lang english

chinese:
	go run greeter.go  -lang chinese

swedish:
	go run greeter.go  -lang swedish



