LDDIR = -lapue

pipe48: code_4_8.cpp
	g++ ${LDDIR} code_4_8.cpp -o pipe48 -g

pipe414: code_4_14.cpp
	g++ ${LDDIR} code_4_14.cpp -o pipe414 -g

pipe415: code_4_15.cpp
	g++ ${LDDIR} code_4_15.cpp -o pipe415 -g

pipe417: code_4_17.cpp
	g++ ${LDDIR} code_4_17.cpp -o pipe417 -g

pipe423: code_4_23.cpp
	g++ ${LDDIR} code_4_23.cpp -o pipe423 -g

pipe424: code_4_24.cpp
	g++ ${LDDIR} code_4_24.cpp -o pipe424 -g

clean:
	rm -f pipe48 pipe414 pipe415 pipe417 pipe423 pipe424
